[package]
name = "envee"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.5.60", features = ["derive"] }
shellexpand = "3.1.2"
toml = { version = "1.0.3", features = ["preserve_order"] }

[dev-dependencies]
tempfile = "3.26.0"
