[package]
name = "copy-folder"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
env_logger = "0.11.9"
log = "0.4.29"
rayon = "1.11.0"
rfd = "0.17.2"

[dev-dependencies]
rand = "0.10.0"
tempfile = "3.26.0"
